version: '3.4'

networks:
  cluster-network:
    driver: bridge
volumes:
    sqlvolume:
    rnode1:
    rnode2:
services:
  shoponline.api:
    image: ${DOCKER_REGISTRY-}shoponlineapi
    build:
      context: .
      dockerfile: ShopOnline.Api/Dockerfile
    networks:
        - cluster-network
    ports:
        - "49456:443"
        - "49455:80"
    depends_on:
        - sqldb
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=2Secure*Password2
        - ACCEPT_EULA=Y
    networks:
        - cluster-network
    hostname: sqldb
    volumes:
        - sqlvolume:/var/opt/mssql
    ports:
        - "1440:1433"