version: '3.4'

networks:
  cluster-network:
    driver: bridge
volumes:
    sqlvolume:
    web:
services:
  shoponline.webserver:
    image: ${DOCKER_REGISTRY-}shoponlinewebserver
    build:
      context: .
      dockerfile: ShopOnline.WebServer/Dockerfile
    networks:
        - cluster-network
    hostname: shoponline.webserver
    ports:
        - "43331:80"
        - "43330:443"
    depends_on:
        - shoponline.api
  shoponline.api:
    image: ${DOCKER_REGISTRY-}shoponlineapi
    build:
      context: .
      dockerfile: ShopOnline.Api/Dockerfile
    networks:
        - cluster-network
    hostname: shoponline.api
    ports:
        - "43332:443"
        - "43333:80"
    depends_on:
        - sqldb
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=2Secure*Password2
        - ACCEPT_EULA=Y
    networks:
        - cluster-network
    hostname: sqldb
    volumes:
        - sqlvolume:/var/opt/mssql
    ports:
        - "1440:1433"
